### ISSUE TITLE
Wrong rank results when deleted lap in first position

### ISSUE THREAD

**Issue by arnaudmorin** [HazardCreative/RotorHazard-Class-Rank-Best-X-Laps#1]
We had some issue during French National Championships yesterday with the plugin because of deleted laps at first position (see screenshot).
![2024-08-26-152856_1150x850_scrot](https://github.com/user-attachments/assets/3fa8052e-a724-4e0d-b4ba-b80395a75752)

The current computation from code is the following:

1. Extract all laps for a run
2. Loop over all laps starting from position 1 when using Hole Shot as first crossing (thus, discarding lap 0)
3. Keep only the not deleted laps

The loop is always discarding the first lap (position 0), no matter the status of this lap.
If the lap was deleted by the marshal, it will also be discarded, but then, the lap following will not be discarded while it should.
As a result, based on the example screenshot, the best lap for this pilot will be 3.057, which is wrong

One solution to avoid this issue is to click on "clean deleted laps" from marshal tab

One other solution is to fix the code to take that into account

**Comment by HazardCreative** [comment]
Thanks for the report. This should definitely be fixed in the plugin. I need to add a manifest to some of these first-gen plugins, too.
